config/routes.rb
Rails.application.routes.draw do
  resources :news_feeds

  namespace :users do
  	get 'omniauth_callbacks/facebook', as: "facebook_login"
  end

  root "home_pages#main"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
end

app/models/news_feed.rb
class NewsFeed < ActiveRecord::Base
	scope :news_category, -> (tagname){where("tagname LIKE ?", "%#{tagname}%")}

	belongs_to :user

	def set_news_category(tagname_to_set)
		self.tagname = tagname_to_set
		self.save!
	end 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook] 

  has_many :news_feeds

  def self.find_for_facebook_oauth(auth)
	  where(auth.slice(:provider, :uid)).first_or_create do |user|
	    user.provider = auth.provider
	    user.uid = auth.uid
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    user.name = auth.info.name   # assuming the user model has a name
	    #user.image = auth.info.image # assuming the user model has an image
	  end
	end

	def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end 

  def online?
    $redis_onlines.exists( self.id )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  after_filter :set_online

  helper_method :all_who_are_in_touch

  def after_sign_in_path_for(resource)
  	news_feeds_path
	end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
  
  private

  def set_online
    if !!current_user
      # не нужно значение, нужен только ключ
        $redis_onlines.set( current_user.id, nil, ex: 1 )
      # `ex: 10*60` - устанавливаем время жизни ключа - 10 минут, через 10 мину ключ удалиться
    end
  end

  def all_who_are_in_touch
    $redis_onlines.keys.count
    # => [ "123", "234", "1", "23" ]
    # вернёт массив с id онлайн пользователей
  end

end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  def main
    render 'home_pages/main'
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/news_feeds_controller.rb
class NewsFeedsController < ApplicationController
  before_action :set_news_feed, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /news_feeds
  # GET /news_feeds.json
  def index
    if params[:search]
      @news_feeds = NewsFeed.news_category(params[:search]).order("created_at DESC")
    else
      @news_feeds = NewsFeed.all.order('created_at DESC')
    end
  end

  # GET /news_feeds/1
  # GET /news_feeds/1.json
  def show
  end

  # GET /news_feeds/new
  def new
    @news_feed = NewsFeed.new
  end

  # GET /news_feeds/1/edit
  def edit
  end

  # POST /news_feeds
  # POST /news_feeds.json
  def create
    @news_feed = NewsFeed.new(news_feed_params)

    respond_to do |format|
      if @news_feed.save
        format.html { redirect_to @news_feed, notice: 'News feed was successfully created.' }
        format.json { render :show, status: :created, location: @news_feed }
      else
        format.html { render :new }
        format.json { render json: @news_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_feeds/1
  # PATCH/PUT /news_feeds/1.json
  def update
    respond_to do |format|
      if @news_feed.update(news_feed_params)
        format.html { redirect_to @news_feed, notice: 'News feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @news_feed }
      else
        format.html { render :edit }
        format.json { render json: @news_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_feeds/1
  # DELETE /news_feeds/1.json
  def destroy
    @news_feed.destroy
    respond_to do |format|
      format.html { redirect_to news_feeds_url, notice: 'News feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news_feed
      @news_feed = NewsFeed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_feed_params
      params.require(:news_feed).permit(:title, :text, :tagname)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
    else
      render 'edit' 
    end
  end

  private 

  def user_params
    params.require(:user).permit(:name, :email, :about)
  end  

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/news_feeds_helper.rb
module NewsFeedsHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/views/layouts/_messages.html.erb
<div class='container'>
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
</div>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Newsfeed', root_path, class: 'navbar-brand', id: 'logo'%>
      <li class="divider"></li>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav pull-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
	<%= form_tag(news_feeds_path, :method => "get", id: "search-form", class: "navbar-form navbar-left") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search For news", class: "form-control"%>
  <%= button_tag "Search", :name => nil, class: "btn btn-default" %>
<% end %>
  <li><%= link_to 'New News feed', new_news_feed_path %></li>
  <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">User profile<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Go to my profile', current_user %></li>
            <li><%= link_to 'Edit account', edit_user_registration_path %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
            <li><%= link_to 'Show news', news_feeds_path %></li>
          </ul>
        </li>
  </ul>

<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
  <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %><li>
  <li>><%= link_to "Online users: #{all_who_are_in_touch}", root_path %></li>
<% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Newsfeed" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Newsfeed" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
 
  <header>
      <%= render 'layouts/navigation' %>
  </header>
  <body>
    <div class='conrainer'>
      <span role="main">
         <%= render 'layouts/messages' %>
      </span>
    <span>  
    </span>
  </div>
  <%= yield %>
  </body>
</html>

app/views/news_feeds/_form.html.erb
<%= simple_form_for(@news_feed) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :text %>
    <%= f.input :tagname %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/news_feeds/edit.html.erb
<h1>Editing news_feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @news_feed %> |
<%= link_to 'Back', news_feeds_path %>

app/views/news_feeds/index.html.erb
<center>
  <h1>Listing news_feeds</h1>
</center>
<% @news_feeds.each do |news_feed| %>      
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title"><%= news_feed.title %></h2>
        </div>
        <div class="panel-body">
          <p><%= news_feed.text %></p>
        </div>
        <div class="panel-footer">
          <p>Created at: <%= news_feed.created_at%></p>
          <p>Tag: <%= news_feed.tagname %></p> 
          <p><%= link_to 'Show details', news_feed %></p>
        </div>
      </div>  
    </div>
</div>
<% end %>

app/views/news_feeds/new.html.erb
<h1>New news_feed</h1>

<%= render 'form' %>

<%= link_to 'Back', news_feeds_path %>

app/views/news_feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news_feed.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @news_feed.text %>
</p>

<%= link_to 'Back', news_feeds_path %>

app/views/users/show.html.erb
<div class="row pull-center">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
    	<%= gravatar_for(@user)%>
      <div class="caption">
        <h3>Name: <%= @user.name if @user.name %></h3>
        <p>Data of registration: <%= @user.created_at%></p>
        <p>About me: <%= @user.about%></p>
        <p><%=link_to("Edit Information", edit_user_registration_path, class: "btn btn-primary", role: "button")%></p>
      </div>
    </div>
  </div>
</div>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>